// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arsgktzwymaakoaharfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyc2drdHp3eW1hYWtvYWhhcmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzcyMDAsImV4cCI6MjA1Mzg1MzIwMH0.c1QceeFQQLVdE-Iy26O1ctSsyM2ZZYYpLIi-lyUMZvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);